# Generated by Django 3.2.6 on 2021-08-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_alter_user_details_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='District',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Vaccine_Center',
        ),
        migrations.AddField(
            model_name='user_details',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registration.district'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='vaccine_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registration.vaccine_center'),
        ),
    ]
