# Generated by Django 3.2.6 on 2021-08-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_auto_20210824_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='Person',
        ),
    ]
