# Generated by Django 3.2.6 on 2021-08-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_rename_user_details_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Address',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='person',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='Contact_Number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='Email',
            field=models.CharField(max_length=250),
        ),
    ]
