# Generated by Django 3.2.6 on 2021-08-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
