# Generated by Django 3.2.6 on 2021-09-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0011_person_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Created_by',
        ),
    ]
